feat: added dynatrace oneagent
Rookout/terraform-aws-rookout-deployment pull request #64
Opened 2023-08-31 12:34 UTC by gosharo

2023-08-31 12:35 UTC, gosharo commented
/jira open task

2023-09-04 22:11 UTC, ElDuderinos requested changes

2023-09-04 22:11 UTC, ElDuderinos commented on templates/controller_task_def.tpl
> +            "value": "https://ozg05024.live.dynatrace.com/api"
Let's not have this as part of the default URL for the module.
The module should allow users to use their own URL.

2023-09-05 02:39 UTC, gosharo commented on templates/controller_task_def.tpl
> +            "value": "https://ozg05024.live.dynatrace.com/api"
oh sure.. on that, thanks !

2023-09-05 05:59 UTC, ElDuderinos approved these changes

2023-09-05 06:31 UTC, merged